# Generated by Django 3.1.7 on 2021-03-18 09:24

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300, verbose_name='comment')),
                ('location_state', models.CharField(max_length=100, null=True, verbose_name='state')),
                ('location_city', models.CharField(max_length=100, null=True, verbose_name='city')),
                ('date', models.DateTimeField(verbose_name='event date')),
                ('duration', models.PositiveIntegerField(verbose_name='gig duration, in minutes')),
                ('gig_type', models.IntegerField(choices=[(1, 'Party'), (2, 'Wedding'), (3, 'Radio Play'), (4, 'Birthday Party'), (5, 'Mitzvah'), (6, 'Bar Night'), (7, 'Club'), (8, 'Religious Event'), (9, 'Picnic'), (10, 'Family Reunion'), (11, 'Other')], verbose_name='gig type')),
                ('music_list', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), null=True, size=None, verbose_name='music list')),
                ('listeners', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), choices=[(1, '17 and Younger'), (2, '18-35'), (3, '36-50'), (4, '50 and Older')], null=True, size=None, verbose_name='listeners')),
                ('clean_mix', models.BooleanField(null=True, verbose_name='clean mix?')),
                ('virtual_mix', models.BooleanField(null=True, verbose_name='virtual mix?')),
                ('add_ons_microphone', models.BooleanField(null=True, verbose_name='extra microphone?')),
                ('add_ons_fog_machine', models.BooleanField(null=True, verbose_name='extra fog machine?')),
                ('add_ons_power_cords', models.BooleanField(null=True, verbose_name='extra power cords?')),
                ('add_ons_speakers', models.BooleanField(null=True, verbose_name='extra speakers?')),
                ('out_door_play', models.IntegerField(choices=[(1, 'Radio Play'), (2, 'Picnic Area'), (3, '**Other')], verbose_name='out_door_play')),
                ('in_door_play', models.IntegerField(choices=[(1, '1000 Squ/ft or Less'), (2, '1400 Squ/ft'), (3, '1600 Squ/ft'), (4, '2000 Squ/ft'), (5, '2200 Squ/ft'), (6, '2500 Squ/ft'), (7, '3000 Squ/ft'), (8, '3100 Squ/ft'), (9, '3500 Squ/ft and More')], verbose_name='in_door_play')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Decline'), (3, 'Accept'), (4, 'Timeout')], default=1, verbose_name='status')),
                ('decline_comment', models.TextField(blank=True, max_length=300, null=True, verbose_name='decline comment')),
                ('is_payed', models.BooleanField(default=False, verbose_name='payed or not?')),
                ('payment_intent_id', models.CharField(editable=False, max_length=200, verbose_name='payment intent ID')),
                ('payment_intent_client_secret', models.CharField(editable=False, max_length=200, verbose_name='payment intent client secret')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_booker', to='users.account')),
                ('account_dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_dj', to='users.account')),
            ],
        ),
    ]
