# Generated by Django 3.1.7 on 2021-03-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(null=True, verbose_name='event time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True, verbose_name='event date'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('account_dj', 'date')},
        ),
    ]
