# Generated by Django 3.1.7 on 2021-03-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_price_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not paid'), (2, 'Paid'), (3, 'Declined by booker'), (4, 'Declined by DJ'), (5, 'Success')], default=1, verbose_name='status'),
        ),
    ]
