# Generated by Django 3.1.7 on 2021-03-30 02:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210322_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='listeners',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, '17 and Younger'), (2, '18-35'), (3, '36-50'), (4, '50 and Older')]), null=True, size=None, verbose_name='listeners'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='music_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'EDM / House'), (2, 'Hip-Pop / Rap'), (3, 'Top 40'), (4, 'Soca/African'), (5, 'Rock'), (6, 'R&B / Soul'), (7, 'Latin'), (8, 'Country'), (9, 'Oldies'), (10, '80s'), (11, '90s'), (12, 'Funk / Disco'), (13, 'Metal'), (14, 'Other')]), null=True, size=None, verbose_name='music list'),
        ),
    ]
