# Generated by Django 3.1.7 on 2021-04-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210409_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='out_door_play',
            field=models.IntegerField(choices=[(1, 'Radio Play'), (2, 'Picnic Area'), (3, '**Other'), (4, 'Not Applicable')], verbose_name='out_door_play'),
        ),
    ]
