# Generated by Django 3.1.7 on 2021-04-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20210412_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adjustment_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='gig minutes adjusted to minimal booking price, in minutes'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booker_fee',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Booker fee in $_'),
        ),
        migrations.AddField(
            model_name='booking',
            name='dj_fee',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='DJ fee in $_'),
        ),
    ]
