# Generated by Django 3.1.7 on 2021-05-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20210423_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adjustment_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Adjusted gig minutes added'),
        ),
    ]
