# Generated by Django 3.1.7 on 2021-05-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20210504_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='gig duration, min'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not paid'), (2, 'Paid'), (3, 'Declined by booker'), (4, 'Declined by DJ'), (5, 'Success'), (6, 'Completed'), (7, 'Accepted by DJ'), (8, 'Canceled by booker'), (9, 'Canceled by DJ')], default=1, verbose_name='status'),
        ),
    ]
