# Generated by Django 3.1.7 on 2021-05-04 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0013_auto_20210504_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Сумма')),
                ('status', models.IntegerField(choices=[(1, 'In review'), (2, 'Approved'), (3, 'Rejected'), (4, 'Canceled')], default=1, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.PositiveSmallIntegerField(choices=[(1, 'Payment for Booking by the booker'), (2, 'Payment to the performer for the Booking'), (3, 'Withdrawal of the money from balance')], editable=False, verbose_name='Transaction purpose')),
                ('amount', models.IntegerField(default=0, editable=False, verbose_name='Transaction sum')),
                ('entity_pk', models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Transaction object ID')),
                ('is_hold', models.BooleanField(blank=True, default=False, verbose_name='Transaction hold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
