# Generated by Django 3.1.7 on 2021-05-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20210505_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_fee',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Stripe fee in $'),
        ),
    ]
