# Generated by Django 3.1.7 on 2021-05-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20210506_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stripe_fee',
        ),
    ]
