# Generated by Django 3.1.7 on 2021-05-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_remove_booking_stripe_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='decline_comment',
            field=models.TextField(blank=True, null=True, verbose_name='decline comment'),
        ),
    ]
