# Generated by Django 3.1.7 on 2021-05-12 17:16

from datetime import datetime, timedelta, date, time

from django.db import migrations
import django.contrib.postgres.fields
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Booking = apps.get_model("booking", "Booking")
    db_alias = schema_editor.connection.alias

    def _calculate_busy_dates(date: date, time: time, duration: int):
        end_date = datetime.combine(
            date, time) + timedelta(minutes=duration)
        busy_dates = [date + timedelta(days=x)
                      for x in range((end_date.date() - date).days + 1)]
        return busy_dates

    for booking in Booking.objects.using(db_alias).all():
        booking.dj_busy_dates = _calculate_busy_dates(
            booking.date,
            booking.time,
            booking.duration
        )
        booking.save()


def reverse_func(apps, schema_editor):
    """
    dj_busy_dates field will be simply deleted if migration is reversed
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20210507_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dj_busy_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]


