# Generated by Django 3.1.7 on 2021-05-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20210506_1802'),
        ('booking', '0019_auto_20210507_1332'),
    ]

    operations = [
    ]
