# Generated by Django 3.1.7 on 2021-05-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20210507_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='destination_card',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
