# Generated by Django 3.1.7 on 2021-05-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_withdrawal_destination_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
        ),
    ]
