# Generated by Django 3.1.7 on 2021-05-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20210512_1716'),
        ('booking', '0020_merge_20210513_1103'),
    ]

    operations = [
    ]
