# Generated by Django 3.1.7 on 2021-05-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_merge_20210514_1321'),
        ('booking', '0021_auto_20210514_0816'),
    ]

    operations = [
    ]
