# Generated by Django 3.1.7 on 2021-05-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20210517_0633'),
        ('booking', '0022_merge_20210514_1359'),
        ('booking', '0022_auto_20210517_0959'),
    ]

    operations = [
    ]
