# Generated by Django 3.1.7 on 2021-05-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20210518_0653'),
        ('booking', '0022_merge_20210514_1359'),
    ]

    operations = [
    ]
