# Generated by Django 3.1.7 on 2021-05-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_merge_20210519_0844'),
        ('booking', '0023_merge_20210519_0900'),
    ]

    operations = [
    ]
