# Generated by Django 3.1.7 on 2021-05-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_merge_20210519_0812'),
        ('booking', '0024_merge_20210519_1109'),
    ]

    operations = [
    ]
