# Generated by Django 3.1.7 on 2021-05-25 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_merge_20210519_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dispute', serialize=False, to='booking.booking')),
                ('status', models.IntegerField(choices=[(1, 'Created by booker'), (2, 'Waiting for DJ testimonials'), (3, 'Waiting for decision from staff'), (4, 'Booker conceded'), (5, 'Performer conceded'), (6, 'Resolved by staff')], default=1)),
                ('booker_testimonial', models.TextField()),
                ('dj_testimonial', models.TextField(blank=True, null=True)),
                ('decision', models.TextField(blank=True, null=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
