# Generated by Django 3.1.7 on 2021-05-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_auto_20210525_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.IntegerField(choices=[(1, 'Waiting for DJ testimonials'), (2, 'Waiting for decision from staff'), (3, 'Booker conceded'), (4, 'Performer conceded'), (5, 'Resolved by staff')], default=1),
        ),
    ]
