# Generated by Django 3.1.7 on 2021-05-26 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_auto_20210525_1003'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dispute',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='dispute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
