# Generated by Django 3.1.7 on 2021-05-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_auto_20210526_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dispute',
        ),
    ]
