# Generated by Django 3.1.7 on 2021-05-31 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_delete_dispute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingreview',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking.booking'),
        ),
    ]
