# Generated by Django 3.2.4 on 2021-06-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_auto_20210601_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingreview',
            name='is_by_booker',
            field=models.BooleanField(default=True),
        ),
    ]
