# Generated by Django 3.2.4 on 2021-06-07 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_bookingreview_is_by_booker'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
