# Generated by Django 3.2.4 on 2021-06-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_bookingreview_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='can_be_rated',
            field=models.BooleanField(default=True),
        ),
    ]
