# Generated by Django 3.2.4 on 2021-10-21 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_transaction_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingChangeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, null=True, verbose_name='Field')),
                ('value_before', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Value Before')),
                ('value_after', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Value After')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_records', to='booking.booking')),
            ],
        ),
    ]
