# Generated by Django 3.2.4 on 2021-10-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_bookingchangerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='sum_to_pay_from_balance',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Sum to pay from balance (not stripe) in $'),
        ),
    ]
