# Generated by Django 3.2.4 on 2021-11-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_booking_is_fully_paid_from_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingchangerecord',
            name='is_by_staff',
            field=models.BooleanField(default=False, verbose_name='By Staff'),
        ),
    ]
