# Generated by Django 3.2.4 on 2021-11-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_bookingchangerecord_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price_per_hour',
            field=models.FloatField(default=0, verbose_name='Price per hour in $_'),
        ),
    ]
