# Generated by Django 3.2.4 on 2021-11-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_alter_booking_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Event Address'),
        ),
    ]
