# Generated by Django 3.2.4 on 2021-11-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0044_booking_event_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode_type', models.IntegerField(choices=[(1, 'Fixed amount'), (2, 'Percent')], verbose_name='Promocode Type')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
