# Generated by Django 3.2.4 on 2021-11-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0045_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
