# Generated by Django 3.2.4 on 2021-11-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_promocode_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Promocode'),
        ),
    ]
