# Generated by Django 3.2.4 on 2021-11-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0047_promocode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Code'),
        ),
    ]
