# Generated by Django 3.2.4 on 2021-11-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0048_alter_promocode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
