# Generated by Django 3.2.4 on 2021-11-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_promocode_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='bookings',
            field=models.ManyToManyField(related_name='promocodes_set', related_query_name='promocode', to='booking.Booking', verbose_name='bookings'),
        ),
    ]
