# Generated by Django 3.2.4 on 2021-11-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_promocode_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='max_application_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
