# Generated by Django 3.2.4 on 2021-11-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_promocode_max_application_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
