# Generated by Django 3.2.4 on 2021-11-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0053_auto_20211115_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='applied_discounts',
            field=models.JSONField(null=True, verbose_name='Applied discounts'),
        ),
    ]
