# Generated by Django 3.2.4 on 2021-11-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0054_booking_applied_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='applied_discounts',
            field=models.JSONField(blank=True, null=True, verbose_name='Applied discounts'),
        ),
    ]
